/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-18 10:06:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1692240732011L));
    _jspx_dependants.put("jar:file:/F:/iclass0419/projectC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectC/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<!--\n");
      out.write("	Apex by Pixelarity\n");
      out.write("	pixelarity.com | hello@pixelarity.com\n");
      out.write("	License: pixelarity.com/license\n");
      out.write("-->\n");
      out.write("<!-- 웹사이트 전체적인 틀-->\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title>BELLO</title>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"keywords\" content=\"\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/main.css?=3\" />\n");
      out.write("</head>\n");
      out.write("<body class=\"is-preload\">\n");
      out.write("\n");
      out.write("	<!-- 					<a class=\"logo\" href=\"index.html\"><strong>Bello</strong></a> -->\n");
      out.write("	<!-- Header -->\n");
      out.write("	<header id=\"header\">\n");
      out.write("		<div>\n");
      out.write("			<div class=\"inner\">\n");
      out.write("				<ul>\n");
      out.write("							<li><a href=\"list.jsp\">고객목록</a></li>\n");
      out.write("							<li><a href=\"clothesList.jsp\">상품등록</a></li>\n");
      out.write("	<!-- 로그인 폼 위에 카카오 로그인 버튼 추가 -->\n");
      out.write("							<li><a href=\"adminNotice.jsp\">공지사항</a></li>\n");
      out.write("							<li><a href=\"../CustomerQnA/QnA.jsp\">고객센터</a></li>\n");
      out.write("							<li><a href =\"../login/logout.jsp\">로그아웃</a></li>\n");
      out.write("						</ul>		\n");
      out.write("			</div>\n");
      out.write("			<div class=\"first\">\n");
      out.write("				<ul>\n");
      out.write("					<li><a href=\"../clothes/clothe_outer.jsp\">OUTER</a></li>\n");
      out.write("					<li><a href=\"../clothes/clothe_top.jsp\">TOP</a></li>\n");
      out.write("					<li><a href=\"../clothes/clothe_pants.jsp\">PANTS</a></li>\n");
      out.write("					<li><a href=\"../clothes/clothe_shoes.jsp\">SHOES</a></li>\n");
      out.write("					<li><a href=\"../styling/stylingList.jsp\">STYLING</a> <!-- 스타일링 배너 -->\n");
      out.write("						\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("	<!-- Search Bar -->\n");
      out.write("    <div id=\"search\">\n");
      out.write("        <a class=\"logo\" href=\"admin.jsp\"><strong>Bello</strong></a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Banner -->\n");
      out.write("    <div id=\"banner\">\n");
      out.write("        <!-- Banner 내용 추가 -->\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Main -->\n");
      out.write("    <div class=\"inner\">\n");
      out.write("        <!-- Content -->\n");
      out.write("        <div id=\"content\">\n");
      out.write("            <!-- Posts -->\n");
      out.write("            <header>\n");
      out.write("                <h1>BEST</h1>\n");
      out.write("            </header>\n");
      out.write("           <section class=\"posts\">\n");
      out.write("                <!-- 상품 목록 표시 -->\n");
      out.write("                <div class=\"image fit\" style=\"text-align: center;\">\n");
      out.write("                    <a href=\"clothes/clothes_detail.jsp?clothesNum=10003\"><img src=\"/imageupload/3.jpg\" alt=\"\" /></a>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=10003\">테일러드 크롭 반팔 자켓</a></p>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=10003\">");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("</a></p>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"image fit\" style=\"text-align: center;\">\n");
      out.write("                    <a href=\"clothes/clothes_detail.jsp?clothesNum=20003\"><img src=\"/imageupload/6.jpg\" alt=\"\" /></a>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=20003\">파우더 허그미 리본 볼레로 시스루 부클 브이넥 긴팔 니트</a></p>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=20003\">");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("</a></p>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"image fit\" style=\"text-align: center;\">\n");
      out.write("                    <a href=\"clothes/clothes_detail.jsp?clothesNum=70005\"><img src=\"/imageupload/59.jpg\" alt=\"\" /></a>\n");
      out.write("                     <p><a href=\"clothes/clothes_detail.jsp?clothesNum=70005\">미니 데님 스커트</a></p>\n");
      out.write("                     <p><a href=\"clothes/clothes_detail.jsp?clothesNum=70005\">");
      if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_page_context))
        return;
      out.write("</a></p>\n");
      out.write("                </div>\n");
      out.write("                <!-- 다른 상품들 추가 -->\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <!-- Mini Posts -->\n");
      out.write("            <header>\n");
      out.write("                <h1>NEW</h1>\n");
      out.write("            </header>\n");
      out.write("             <section class=\"mini-posts\">\n");
      out.write("                <!-- 상품 목록 표시 -->\n");
      out.write("                <div class=\"image fit\" style=\"text-align: center;\">\n");
      out.write("                    <a href=\"clothes/clothes_detail.jsp?clothesNum=10002\"><img src=\"/imageupload/2.jpg\" alt=\"\" /></a>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=10002\">트렌치 플리츠 코트 자켓 원피스</a></p>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=10002\">");
      if (_jspx_meth_fmt_005fformatNumber_005f3(_jspx_page_context))
        return;
      out.write("</a></p>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"image fit\" style=\"text-align: center;\">\n");
      out.write("                    <a href=\"clothes/clothes_detail.jsp?clothesNum=40011\"><img src=\"/imageupload/23.jpg\" alt=\"\" /></a>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=40011\">위티브 카라 원피스</a></p>\n");
      out.write("                      <p><a href=\"clothes/clothes_detail.jsp?clothesNum=40011\">");
      if (_jspx_meth_fmt_005fformatNumber_005f4(_jspx_page_context))
        return;
      out.write("</a></p>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"image fit\" style=\"text-align: center;\">\n");
      out.write("                    <a href=\"clothes/clothes_detail.jsp?clothesNum=90012\"><img src=\"/imageupload/93.jpg\" alt=\"\" /></a>\n");
      out.write("                    <p><a href=\"clothes/clothes_detail.jsp?clothesNum=90012\">파라슈트 나일론 투웨이 조거 카고 팬츠</a></p>\n");
      out.write("                     <p><a href=\"clothes/clothes_detail.jsp?clothesNum=90012\">");
      if (_jspx_meth_fmt_005fformatNumber_005f5(_jspx_page_context))
        return;
      out.write("</a></p>\n");
      out.write("                </div>\n");
      out.write("                <!-- 다른 상품들 추가 -->\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer id=\"footer\">\n");
      out.write("        <h4>&copy; Untitled Corporation. All rights reserved. Lorem ipsum dolor sit amet nullam.</h4>\n");
      out.write("        <ul>\n");
      out.write("            <li class=\"icon solid fa-map-marker-alt\"></li>\n");
      out.write("            <li class=\"icon solid fa-envelope\"></li>\n");
      out.write("            <li class=\"icon brands fa-twitter\"></li>\n");
      out.write("            <li class=\"icon solid fa-phone\"></li>\n");
      out.write("        </ul>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("	<!-- Scripts -->\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/browser.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/breakpoints.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/util.js\"></script>\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /admin/admin.jsp(73,79) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue("31120");
      // /admin/admin.jsp(73,79) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("currency");
      // /admin/admin.jsp(73,79) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setCurrencySymbol("￦");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /admin/admin.jsp(78,79) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue("19900");
      // /admin/admin.jsp(78,79) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setType("currency");
      // /admin/admin.jsp(78,79) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setCurrencySymbol("￦");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
      // /admin/admin.jsp(83,78) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue("21900");
      // /admin/admin.jsp(83,78) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setType("currency");
      // /admin/admin.jsp(83,78) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setCurrencySymbol("￦");
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f3.setParent(null);
      // /admin/admin.jsp(97,79) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setValue("64800");
      // /admin/admin.jsp(97,79) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setType("currency");
      // /admin/admin.jsp(97,79) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setCurrencySymbol("￦");
      int _jspx_eval_fmt_005fformatNumber_005f3 = _jspx_th_fmt_005fformatNumber_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f3);
      _jspx_th_fmt_005fformatNumber_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f4_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f4.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f4.setParent(null);
      // /admin/admin.jsp(102,79) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f4.setValue("29000");
      // /admin/admin.jsp(102,79) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f4.setType("currency");
      // /admin/admin.jsp(102,79) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f4.setCurrencySymbol("￦");
      int _jspx_eval_fmt_005fformatNumber_005f4 = _jspx_th_fmt_005fformatNumber_005f4.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f4);
      _jspx_th_fmt_005fformatNumber_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f4, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f5_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f5.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f5.setParent(null);
      // /admin/admin.jsp(107,78) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f5.setValue("24560");
      // /admin/admin.jsp(107,78) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f5.setType("currency");
      // /admin/admin.jsp(107,78) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f5.setCurrencySymbol("￦");
      int _jspx_eval_fmt_005fformatNumber_005f5 = _jspx_th_fmt_005fformatNumber_005f5.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f5);
      _jspx_th_fmt_005fformatNumber_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f5, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f5_reused);
    }
    return false;
  }
}
