/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-06 08:41:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shopping;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cart2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/cart2.css?=3\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/main.css?=3\"/>\r\n");
      out.write("<title>장바구니</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("			<header id=\"header\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"index.html\">공지사항</a></li>\r\n");
      out.write("							<li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("							<li><a href=\"cart.jsp\">장바구니</a></li>\r\n");
      out.write("							<li><a href=\"elements.html\">고객센터</a></li>\r\n");
      out.write("						</ul>		\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"first\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">OUTER</a></li>\r\n");
      out.write("							<li><a href=\"#\">TOP</a></li>\r\n");
      out.write("							<li><a href=\"#\">PANTS</a></li>\r\n");
      out.write("							<li><a href=\"#\">SHOES</a></li>\r\n");
      out.write("							<li><a href=\"#\">STYLING</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</header>\r\n");
      out.write("			\r\n");
      out.write("		<!-- Search Bar -->\r\n");
      out.write("			<div id=\"search\">\r\n");
      out.write("			<a class=\"logo\" href=\"index.jsp\"><strong>Bello</strong></a> \r\n");
      out.write("				<!-- <div class=\"inner\">\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<form method=\"post\" action=\"#\">\r\n");
      out.write("							<input type=\"search\" name=\"query\" id=\"query\" value=\"\" placeholder=\"Search our site\" />\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write(" -->			</div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<form name=\"orderform\" id=\"orderform\" method=\"post\" class=\"orderform\" action=\"/Page\" onsubmit=\"return false;\">\r\n");
      out.write("    \r\n");
      out.write("            <input type=\"hidden\" name=\"cmd\" value=\"order\">\r\n");
      out.write("            <div class=\"basketdiv\" id=\"basket\">\r\n");
      out.write("                <div class=\"row head\">\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"check\">선택</div>\r\n");
      out.write("                        <div class=\"img\">이미지</div>\r\n");
      out.write("                        <div class=\"pname\">상품명</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketprice\">가격</div>\r\n");
      out.write("                        <div class=\"num\">수량</div>\r\n");
      out.write("                        <div class=\"sum\">합계</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("    \r\n");
      out.write("                        <div class=\"basketcmd\">삭제</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"split\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("                <div class=\"row data\">\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"check\"><input type=\"checkbox\" name=\"buy\" value=\"260\" checked=\"\" onclick=\"javascript:basket.checkItem();\">&nbsp;</div>\r\n");
      out.write("                        <div class=\"img\"><img src=\"./img/basket1.jpg\" width=\"60\"></div>\r\n");
      out.write("                        <div class=\"pname\">\r\n");
      out.write("                            <span>아우터</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketprice\"><input type=\"hidden\" name=\"p_price\" id=\"p_price1\" class=\"p_price\" value=\"20000\">20,000원</div>\r\n");
      out.write("                        <div class=\"num\">\r\n");
      out.write("                            <div class=\"updown\">\r\n");
      out.write("                                <input type=\"text\" name=\"p_num1\" id=\"p_num1\" size=\"2\" maxlength=\"4\" class=\"p_num\" value=\"2\" onkeyup=\"javascript:basket.changePNum(1);\">\r\n");
      out.write("                                <span><i class=\"fas fa-arrow-alt-circle-up up\"></i></span>\r\n");
      out.write("<span><i class=\"fas fa-arrow-alt-circle-down down\"></i></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sum\">40,000원</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketcmd\"><a href=\"javascript:void(0)\" class=\"abutton\" onclick=\"javascript:basket.delItem();\">삭제</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row data\">\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"check\"><input type=\"checkbox\" name=\"buy\" value=\"261\" checked=\"\" onclick=\"javascript:basket.checkItem();\">&nbsp;</div>\r\n");
      out.write("                        <div class=\"img\"><img src=\"./img/basket2.jpg\" width=\"60\"></div>\r\n");
      out.write("                        <div class=\"pname\">\r\n");
      out.write("                            <span>상의</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketprice\"><input type=\"hidden\" name=\"p_price\" id=\"p_price2\" class=\"p_price\" value=\"19000\">19,000원</div>\r\n");
      out.write("                        <div class=\"num\">\r\n");
      out.write("                            <div class=\"updown\">\r\n");
      out.write("                                <input type=\"text\" name=\"p_num2\" id=\"p_num2\" size=\"2\" maxlength=\"4\" class=\"p_num\" value=\"1\" onkeyup=\"javascript:basket.changePNum(2);\">\r\n");
      out.write("                                <span><i class=\"fas fa-arrow-alt-circle-up up\"></i></span>\r\n");
      out.write("<span><i class=\"fas fa-arrow-alt-circle-down down\"></i></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sum\">19,000원</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketcmd\"><a href=\"javascript:void(0)\" class=\"abutton\" onclick=\"javascript:basket.delItem();\">삭제</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row data\">\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"check\"><input type=\"checkbox\" name=\"buy\" value=\"262\" checked=\"\" onclick=\"javascript:basket.checkItem();\">&nbsp;</div>\r\n");
      out.write("                        <div class=\"img\"><img src=\"./img/basket3.jpg\" width=\"60\"></div>\r\n");
      out.write("                        <div class=\"pname\">\r\n");
      out.write("                            <span>하의</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketprice\"><input type=\"hidden\" name=\"p_price\" id=\"p_price3\" class=\"p_price\" value=\"15200\">15,200원</div>\r\n");
      out.write("                        <div class=\"num\">\r\n");
      out.write("                            <div class=\"updown\">\r\n");
      out.write("                                <input type=\"text\" name=\"p_num3\" id=\"p_num3\" size=\"2\" maxlength=\"4\" class=\"p_num\" value=\"1\" onkeyup=\"javascript:basket.changePNum(3);\">\r\n");
      out.write("                                <span><i class=\"fas fa-arrow-alt-circle-up up\"></i></span>\r\n");
      out.write("<span><i class=\"fas fa-arrow-alt-circle-down down\"></i></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sum\">15,200원</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketcmd\"><a href=\"javascript:void(0)\" class=\"abutton\" onclick=\"javascript:basket.delItem();\">삭제</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"right-align basketrowcmd\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" class=\"abutton\" onclick=\"javascript:basket.delAllItem();\">장바구니비우기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"bigtext right-align sumcount\" id=\"sum_p_num\">상품갯수: 4개</div>\r\n");
      out.write("            <div class=\"bigtext right-align box blue summoney\" id=\"sum_p_price\">합계금액: 74,200원</div>\r\n");
      out.write("    \r\n");
      out.write("            <div id=\"goorder\" class=\"\">\r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("                <div class=\"buttongroup center-align cmd\">\r\n");
      out.write("                    <a href=\"javascript:void(0);\">선택한 상품 주문</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("         <footer id=\"footer\"> \r\n");
      out.write("                  <h4>&copy; Untitled Corporation. All rights reserved. Lorem ipsum dolor sit amet nullam.</h4>\r\n");
      out.write("                           <ul>\r\n");
      out.write("                        <li class=\"icon solid fa-map-marker-alt\">\r\n");
      out.write("                        <li class=\"icon solid fa-envelope\">\r\n");
      out.write("                        <li class=\"icon brands fa-twitter\">\r\n");
      out.write("                        <li class=\"icon solid fa-phone\">\r\n");
      out.write("                        </ul>\r\n");
      out.write("         </footer>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let basket = {\r\n");
      out.write("	    totalCount: 0, \r\n");
      out.write("	    totalPrice: 0,\r\n");
      out.write("	    //체크한 장바구니 상품 비우기\r\n");
      out.write("	    delCheckedItem: function(){\r\n");
      out.write("	        document.querySelectorAll(\"input[name=buy]:checked\").forEach(function (item) {\r\n");
      out.write("	            item.parentElement.parentElement.parentElement.remove();\r\n");
      out.write("	        });\r\n");
      out.write("	        //AJAX 서버 업데이트 전송\r\n");
      out.write("	    \r\n");
      out.write("	        //전송 처리 결과가 성공이면\r\n");
      out.write("	        this.reCalc();\r\n");
      out.write("	        this.updateUI();\r\n");
      out.write("	    },\r\n");
      out.write("	    //장바구니 전체 비우기\r\n");
      out.write("	    delAllItem: function(){\r\n");
      out.write("	        document.querySelectorAll('.row.data').forEach(function (item) {\r\n");
      out.write("	            item.remove();\r\n");
      out.write("	          });\r\n");
      out.write("	          //AJAX 서버 업데이트 전송\r\n");
      out.write("	        \r\n");
      out.write("	          //전송 처리 결과가 성공이면\r\n");
      out.write("	          this.totalCount = 0;\r\n");
      out.write("	          this.totalPrice = 0;\r\n");
      out.write("	          this.reCalc();\r\n");
      out.write("	          this.updateUI();\r\n");
      out.write("	    },\r\n");
      out.write("	    //재계산\r\n");
      out.write("	    reCalc: function(){\r\n");
      out.write("	        this.totalCount = 0;\r\n");
      out.write("	        this.totalPrice = 0;\r\n");
      out.write("	        document.querySelectorAll(\".p_num\").forEach(function (item) {\r\n");
      out.write("	            if(item.parentElement.parentElement.parentElement.previousElementSibling.firstElementChild.firstElementChild.checked == true){\r\n");
      out.write("	                var count = parseInt(item.getAttribute('value'));\r\n");
      out.write("	                this.totalCount += count;\r\n");
      out.write("	                var price = item.parentElement.parentElement.previousElementSibling.firstElementChild.getAttribute('value');\r\n");
      out.write("	                this.totalPrice += count * price;\r\n");
      out.write("	            }\r\n");
      out.write("	        }, this); // forEach 2번째 파라메터로 객체를 넘겨서 this 가 객체리터럴을 가리키도록 함. - thisArg\r\n");
      out.write("	    },\r\n");
      out.write("	    //화면 업데이트\r\n");
      out.write("	    updateUI: function () {\r\n");
      out.write("	        document.querySelector('#sum_p_num').textContent = '상품갯수: ' + this.totalCount.formatNumber() + '개';\r\n");
      out.write("	        document.querySelector('#sum_p_price').textContent = '합계금액: ' + this.totalPrice.formatNumber() + '원';\r\n");
      out.write("	    },\r\n");
      out.write("	    //개별 수량 변경\r\n");
      out.write("	    changePNum: function (pos) {\r\n");
      out.write("	        var item = document.querySelector('input[name=p_num'+pos+']');\r\n");
      out.write("	        var p_num = parseInt(item.getAttribute('value'));\r\n");
      out.write("	        var newval = event.target.classList.contains('up') ? p_num+1 : event.target.classList.contains('down') ? p_num-1 : event.target.value;\r\n");
      out.write("	        \r\n");
      out.write("	        if (parseInt(newval) < 1 || parseInt(newval) > 99) { return false; }\r\n");
      out.write("\r\n");
      out.write("	        item.setAttribute('value', newval);\r\n");
      out.write("	        item.value = newval;\r\n");
      out.write("\r\n");
      out.write("	        var price = item.parentElement.parentElement.previousElementSibling.firstElementChild.getAttribute('value');\r\n");
      out.write("	        item.parentElement.parentElement.nextElementSibling.textContent = (newval * price).formatNumber()+\"원\";\r\n");
      out.write("	        //AJAX 업데이트 전송\r\n");
      out.write("\r\n");
      out.write("	        //전송 처리 결과가 성공이면    \r\n");
      out.write("	        this.reCalc();\r\n");
      out.write("	        this.updateUI();\r\n");
      out.write("	    },\r\n");
      out.write("	    checkItem: function () {\r\n");
      out.write("	        this.reCalc();\r\n");
      out.write("	        this.updateUI();\r\n");
      out.write("	    },\r\n");
      out.write("	    delItem: function () {\r\n");
      out.write("	        event.target.parentElement.parentElement.parentElement.remove();\r\n");
      out.write("	        this.reCalc();\r\n");
      out.write("	        this.updateUI();\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 숫자 3자리 콤마찍기\r\n");
      out.write("	Number.prototype.formatNumber = function(){\r\n");
      out.write("	    if(this==0) return 0;\r\n");
      out.write("	    let regex = /(^[+-]?\\d+)(\\d{3})/;\r\n");
      out.write("	    let nstr = (this + '');\r\n");
      out.write("	    while (regex.test(nstr)) nstr = nstr.replace(regex, '$1' + ',' + '$2');\r\n");
      out.write("	    return nstr;\r\n");
      out.write("	};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
